server:
  port: 8082

spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    defer-datasource-initialization: true
  security:
      user:
         name: ashish
         password: ashish

#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/employeedatabase
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver


  messages: Default property file
#excluding datasource when not ready
#spring:
#  autoconfigure:
#    exclude:
#      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration